//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhetos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerCommandInfo", Namespace="http://schemas.datacontract.org/2004/07/Rhetos")]
    public partial class ServerCommandInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CommandNameField;
        
        private string DataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandName
        {
            get
            {
                return this.CommandNameField;
            }
            set
            {
                this.CommandNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerProcessingResult", Namespace="http://schemas.datacontract.org/2004/07/Rhetos")]
    public partial class ServerProcessingResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Rhetos.ServerCommandResult[] ServerCommandResultsField;
        
        private bool SuccessField;
        
        private string SystemMessageField;
        
        private string UserMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rhetos.ServerCommandResult[] ServerCommandResults
        {
            get
            {
                return this.ServerCommandResultsField;
            }
            set
            {
                this.ServerCommandResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemMessage
        {
            get
            {
                return this.SystemMessageField;
            }
            set
            {
                this.SystemMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserMessage
        {
            get
            {
                return this.UserMessageField;
            }
            set
            {
                this.UserMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerCommandResult", Namespace="http://schemas.datacontract.org/2004/07/Rhetos")]
    public partial class ServerCommandResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DataField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServerApplication")]
public interface IServerApplication
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerApplication/Execute", ReplyAction="http://tempuri.org/IServerApplication/ExecuteResponse")]
    Rhetos.ServerProcessingResult Execute(Rhetos.ServerCommandInfo[] commands);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerApplication/Execute", ReplyAction="http://tempuri.org/IServerApplication/ExecuteResponse")]
    System.Threading.Tasks.Task<Rhetos.ServerProcessingResult> ExecuteAsync(Rhetos.ServerCommandInfo[] commands);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerApplicationChannel : IServerApplication, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerApplicationClient : System.ServiceModel.ClientBase<IServerApplication>, IServerApplication
{
    
    public ServerApplicationClient()
    {
    }
    
    public ServerApplicationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServerApplicationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Rhetos.ServerProcessingResult Execute(Rhetos.ServerCommandInfo[] commands)
    {
        return base.Channel.Execute(commands);
    }
    
    public System.Threading.Tasks.Task<Rhetos.ServerProcessingResult> ExecuteAsync(Rhetos.ServerCommandInfo[] commands)
    {
        return base.Channel.ExecuteAsync(commands);
    }
}
